### ISSUE TITLE
Installing OBB wrong

### ISSUE THREAD

**Issue by hiyall360** [KhunHtetzNaing/GInstallerMaker#1]
For some reason, it extracts the obb file too, when all we want to do is move it to to Android/Obb/(packagename)/

instead, this is what it does:

Android/Obb/(files that were inside the .obb file are all extracted here) 

We don't want to extract it, we want to copy it to that location.

Am I doing something wrong?

**Comment by hiyall360** [comment]
Here is what it does:

![e6522db5b6b16cc066c211aa188aeee5](https://user-images.githubusercontent.com/20654859/161407925-51ae3331-5e98-485a-88ad-8e6c9705758f.png)


As you can see, there should be a package name folder with a .obb file inside, but instead, it extracted the .obb into Android/obb.

**Comment by KhunHtetzNaing** [comment]
This shit is so fucking out of date.

**Comment by hiyall360** [comment]
Sure, but it still works beautifully, and I absolutely love and appreciate it. I currently use it to deliver data file updates, but I'd really like the obb part of the tool to work. Unless you know of any other tools that do the same thing?

**Comment by KhunHtetzNaing** [comment]
You should rewrite it by yourself.
It's not that difficult.
I haven't used B4A for such a long time.

**Comment by hiyall360** [comment]
Awesome, thank you for the permission to do that!
